function config = ag_e3_config()
% AG_E3_CONFIG Single source of truth for the E3 Retina Walker experiment.

config = struct('name', "V3_E3_RetinaWalker", 'seed', 42, 'inputResolution', 448, ...
    'walkerResolution', 448, 'patchSize', [128 128], 'numPatches', 8, ...
    'numVesselPatches', 6, 'numExplorationPatches', 2, ...
    'vesselMethod', "auto", 'actualVesselMethod', "pending", ...
    'minWalkerSeparation', 96, 'preprocessingVersion', "preprocessFundus-v1", ...
    'cacheSaveFrequency', 250, 'localFeatureLayer', "res3b3_relu", ...
    'localFeatureDim', 256, 'fusionDim', 512, 'dropout', 0.30, ...
    'aggregation', "mean", 'initialCheckpoint', "V3_E1_HighResFOV448.mat", ...
    'optimizer', "sgdm", 'learningRate', 2e-5, 'fineTuneLearningRate', 5e-6, ...
    'momentum', 0.9, 'l2Regularization', 1e-4, 'batchSize', 1, ...
    'epochs', 4, 'freezeEpochs', 2, 'verboseFrequency', 100, ...
    'failureExamplesPerType', 3, 'fovCrop', true, 'inputChannels', "RGB", ...
    'rdrHead', false, 'ordinalHead', false, 'hardMining', false, ...
    'augmentation', "synchronized horizontal reflection; shared mild brightness/contrast; no rotation", ...
    'selectionObjective', "validation balanced accuracy", 'useGPU', false);
config.E3 = struct('patchSize', config.patchSize, 'numPatches', config.numPatches, ...
    'numVesselPatches', config.numVesselPatches, ...
    'numExplorationPatches', config.numExplorationPatches, ...
    'vesselMethod', config.vesselMethod, 'aggregation', config.aggregation, ...
    'initialCheckpoint', config.initialCheckpoint, ...
    'localBackbone', "E1 ResNet-101 stem through res3b3_relu", ...
    'cacheWalkerLocations', true, 'fusionDim', config.fusionDim);
config.resumeSignature = ag_e3_resume_signature(config);
end
